server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**, /staffs/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

okta:
  oauth2:
    issuer: https://dev-74709472.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9uc3v29uUXbDyG5d7
    client-secret: 88c5Maz_mxWtV6ywprNNj9GZnghs3kp4EbC7cgrr