server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: Pratham
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri:  https://dev-77584981.okta.com/oauth2/default
    client:
      registration:
        my-internal-client:
          provider: okta
          authorization-grant-type: client_credentials
          scope: internal
          client-id: 0oa7w65a24Px9Oyms5d7
          client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU

      provider:
        okta:
          issuer-uri:  https://dev-77584981.okta.com/oauth2/default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health


  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

retry:
  instances:
    ratingHotelService:
      max-attempts: 3
      wait-duration: 5s

ratelimiter:
  instances:
    userRateLimiter:
      limit-refresh-period: 4s #in doubt
      limit-for-period: 2 #in doubt
      timeout-duration: 5s #in doubt

okta:
  oauth2:
    issuer: https://dev-74709472.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9uc3v29uUXbDyG5d7
    client-secret: 88c5Maz_mxWtV6ywprNNj9GZnghs3kp4EbC7cgrr
